name: Manual CI Steps (Separate Playbooks)

on:
  workflow_dispatch:
    inputs:
      step:
        description: 'Select step to run'
        required: true
        type: choice
        options:
          - 'build'
          - 'test'
          - 'quality-check'
          - 'package'
          - 'docker-build'
          - 'all'

env:
  JAVA_VERSION: '21'
  ANSIBLE_VERSION: '2.15'

jobs:
  run-step:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install "ansible==${{ env.ANSIBLE_VERSION }}.*"
          ansible --version

      - name: Install Ansible collections
        run: |
          cd ansible
          ansible-galaxy collection install -r requirements.yml

      - name: Run selected step
        run: |
          cd ansible
          case "${{ github.event.inputs.step }}" in
            build)
              ansible-playbook playbooks/build.yml
              ;;
            test)
              ansible-playbook playbooks/test.yml
              ;;
            quality-check)
              ansible-playbook playbooks/quality-check.yml
              ;;
            package)
              ansible-playbook playbooks/package.yml
              ;;
            docker-build)
              ansible-playbook playbooks/docker-build.yml
              ;;
            all)
              ansible-playbook playbooks/ci-pipeline.yml
              ;;
          esac
