- name: Add Docker repository
  command:
    cmd: dnf config-manager --add-repo "{{ docker_repo_url }}"
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Update package cache after adding repository
  ansible.builtin.dnf:
    update_cache: yes

- name: Install Docker and dependencies
  ansible.builtin.dnf:
    name: "{{ docker_packages }}"
    state: latest
  with_items: "{{ docker_packages }}"

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    group: docker

- name: Start Docker
  service:
    name: docker
    state: started
    enabled: yes