db_name: ""
db_user: ""
db_pass: ""

postgres_host: "127.0.0.1"
postgres_port: 5432
postgres_admin_user: "postgres"
vault_psql_adm_pass: ""
encoding: "UTF-8"
lc_collate: "en_US.UTF-8"
lc_ctype: "en_US.UTF-8"
