- block:
    - name: Create Docker secret (LE cert)
      community.docker.docker_secret:
        name: wildcard_crt
        data_src: "/etc/letsencrypt/live/{{ main_domain_name }}/fullchain.pem"
        state: present

    - name: Create Docker secret (LE key)
      community.docker.docker_secret:
        name: wildcard_key
        data_src: "/etc/letsencrypt/live/{{ main_domain_name }}/privkey.pem"
        state: present
  become: true
  when: lets_encrypt
