docker_packages:
  - mc
  - dnf-plugins-core
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - python3-pip

docker_repo_url: https://download.docker.com/linux/centos/docker-ce.repo
docker_repo: docker-ce.repo